#!/usr/bin/env python3
"""Generate the 512px tileable alluvial ground mask.

Requires NumPy and Pillow. The default destination is
public/assets/sand-alluvial.webp. Existing files are never replaced unless
the generated bytes are identical; pass --output to write a separate copy.
"""

from __future__ import annotations

import argparse
from hashlib import sha256
from io import BytesIO
from pathlib import Path

import numpy as np
from PIL import Image


SIZE = 512


def periodic_field(u: np.ndarray, v: np.ndarray, seed: int, terms: list[tuple[int, int, float]]) -> np.ndarray:
    rng = np.random.default_rng(seed)
    values = np.zeros((SIZE, SIZE), dtype=np.float32)
    for fx, fy, weight in terms:
        phase = rng.random() * 6.2831853
        values += weight * np.sin(6.2831853 * (fx * u + fy * v) + phase)
        phase = rng.random() * 6.2831853
        values += weight * 0.55 * np.cos(6.2831853 * (fy * u - fx * v) + phase)
    return values


def create_mask() -> np.ndarray:
    y, x = np.mgrid[0:SIZE, 0:SIZE].astype(np.float32)
    u, v = x / SIZE, y / SIZE

    macro = periodic_field(u, v, 7, [(2, 1, 0.34), (3, -2, 0.23), (5, 4, 0.13), (9, -3, 0.08)])
    mid = periodic_field(u, v, 19, [(13, 8, 0.25), (19, -11, 0.20), (27, 17, 0.12), (41, 5, 0.08)])
    fine = periodic_field(u, v, 31, [(57, 31, 0.24), (83, -47, 0.18), (111, 72, 0.11), (157, 39, 0.06)])
    warp = periodic_field(u, v, 43, [(2, 3, 0.8), (4, -1, 0.45), (7, 5, 0.2)])

    flow = np.sin(2 * np.pi * (7 * u + 2 * v + 0.34 * warp + 0.11 * macro))
    vein = np.exp(-((np.abs(flow) - 0.06) / 0.045) ** 2)
    channels = np.clip(0.48 + 0.18 * macro + 0.20 * mid + 0.12 * fine + 0.16 * vein, 0, 1)
    sediment = np.clip(0.38 + 0.20 * macro + 0.22 * mid + 0.30 * vein, 0, 1)
    grit = np.clip(0.5 + 0.12 * macro + 0.18 * mid + 0.34 * fine, 0, 1)
    return np.uint8(np.clip(np.stack([channels, sediment, grit], axis=-1) * 255, 0, 255))


def encode_webp(rgb: np.ndarray) -> bytes:
    buffer = BytesIO()
    Image.fromarray(rgb).save(buffer, format="WEBP", quality=90, method=6)
    return buffer.getvalue()


def check_seam(webp: bytes) -> tuple[int, int]:
    """Check decoded wrap-adjacent pixels against ordinary pixel neighbors."""
    decoded = np.asarray(Image.open(BytesIO(webp)).convert("RGB"), dtype=np.int16)
    wrap_delta = max(
        int(np.abs(decoded[:, 0] - decoded[:, -1]).max()),
        int(np.abs(decoded[0] - decoded[-1]).max()),
    )
    interior_delta = max(
        int(np.abs(decoded[:, 1:] - decoded[:, :-1]).max()),
        int(np.abs(decoded[1:] - decoded[:-1]).max()),
    )
    if wrap_delta > interior_delta + 2:
        raise RuntimeError(f"Seam check failed: wrap delta {wrap_delta}, interior delta {interior_delta}")
    return wrap_delta, interior_delta


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, help="write to another path instead of public/assets")
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    destination = args.output or project_root / "public/assets/sand-alluvial.webp"
    payload = encode_webp(create_mask())
    wrap_delta, interior_delta = check_seam(payload)

    if destination.exists():
        current = destination.read_bytes()
        if current != payload:
            raise SystemExit(
                f"Refusing to overwrite {destination}: generated bytes differ. "
                "Use --output to inspect a separate generated copy."
            )
        result = "matches existing bytes"
    else:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(payload)
        result = "created"

    print(f"{result}: {destination}")
    print(f"size={len(payload)} sha256={sha256(payload).hexdigest()}")
    print(f"wrap_max_delta={wrap_delta}/255 interior_max_delta={interior_delta}/255")


if __name__ == "__main__":
    main()
